general:
  parameters:
    QSS3KeyPrefix: "temp-aws-tests/"
    QSS3BucketName: "$[taskcat_autobucket]"
    QSS3BucketRegion: "$[taskcat_current_region]"

project:
  name: temp-aws-tests
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  shorten_stack_name: true
  package_lambda: false
tests:
  default:
    template: ./templates/temp.template.yaml
    regions:
    - us-east-2
    parameters:
      RDSUsername: "$[taskcat_random-string]admin"
