AWSTemplateFormatVersion: 2010-09-09
Resources:
  RDSPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Password for the SF RDS instance.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

Outputs:
  input:
    Value: !Sub "{{resolve:secretsmanager:${RDSPassword}:SecretString:password}}"
    Description: secret
